version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: foo@example.com
      PGADMIN_DEFAULT_PASSWORD: insecure
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  pgadmin_data:
