version: "3"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
